import os
import re
import json
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv
from utils import log
import gspread
from google.oauth2.service_account import Credentials
from gspread_dataframe import set_with_dataframe

load_dotenv()

countries = ["SG", "MY", "HK", "ID"]


def get_brand_name(name):
    """Extract brand name by removing country suffix"""
    return name.rsplit(" - ", 1)[0].title()


def get_store_name(url):
    """Extract store name from URL using multiple patterns"""
    patterns = [
        r"(?:\/c\/beauty\/|\/c\/|\/store\/)([^\/\s?#]+)",  # /c/beauty/, /c/, /store/
        r"https?:\/\/[^\/]+\/([^\/\s?#]+)"                # fallback: domain.com/store-name
    ]
    
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            result = match.group(1)
            return result.replace("-", " ").title()
    
    # If no patterns match, return empty string
    return ""


def get_country(raw_key):
    """Extract country code from raw key"""
    suffix = raw_key.rsplit(" - ", 1)[-1].upper()
    if suffix in countries:
        return suffix
    return None


def process_brand_data(data):
    """Process raw data into structured format"""
    result = {}
    
    for raw_key, entries in data.items():
        brand_name = get_brand_name(raw_key)
        country = get_country(raw_key)
        keyword = entries["keyword"]
        store_name = entries["store_name"] if entries["store_name"] else get_store_name(entries["url"])

        unique_key = (brand_name, store_name)

        if unique_key not in result:
            # set up initial row with brand name, store name, and 0 for all countries
            row = {
                "Brand name": brand_name,
                "Keyword": ", ".join(keyword),
                "Store name": store_name,
            }
            for c in countries:
                # create the country and url keys in dict
                row[c] = 0
                row[f"{c} url"] = ""
            result[unique_key] = row

        if country:
            result[unique_key][country.upper()] = 1
            result[unique_key][f"{country.upper()} url"] = entries["url"]
    
    return result


def create_dataframe(result):
    """Convert result dict to formatted dataframe"""
    # Convert result dict to dataframe
    df = pd.DataFrame(result.values())

    # Add 'Status' column with default value "New Added"
    # Note: Chip-style dropdowns are configured manually in Sheets as a workaround for Python library limitations
    df["Store Redirection Status"] = "New Added"

    # Add datetime column with current date and time in dd-mm-yyyy hh:mm:ss format
    current_datetime = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    df["Date Time Added"] = current_datetime

    # set the column order (No column will be generated by Google Sheets SEQUENCE formula)
    df = df[
        ["Brand name", "Keyword", "Store name", "SG", "MY", "HK", "ID", "Store Redirection Status", "Date Time Added", "SG url", "MY url", "HK url", "ID url"]
    ]
    
    return df


def export_to_google_sheets(df):
    """Export dataframe to Google Sheets - append new data if not already exists.

    Requires the GOOGLE_SERVICE_ACCOUNT environment variable to be set to either:
      - A JSON string (the full contents of a service account key file), or
      - A file path pointing to a service account JSON key file.

    Requires GOOGLE_SHEET_URL to be set to the full Google Sheets URL.
    """
    service_account_value = os.getenv("GOOGLE_SERVICE_ACCOUNT")

    if not service_account_value or not service_account_value.strip():
        raise EnvironmentError(
            "GOOGLE_SERVICE_ACCOUNT is not set or empty. "
            "Set it to the service account JSON string or a path to the JSON key file."
        )

    sheet_url = os.getenv("GOOGLE_SHEET_URL")
    if not sheet_url or not sheet_url.strip():
        raise EnvironmentError(
            "GOOGLE_SHEET_URL is not set or empty. "
            "Set it to the full Google Sheets URL."
        )

    scope = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]
    try:
        service_account_info = json.loads(service_account_value)
        creds = Credentials.from_service_account_info(service_account_info, scopes=scope)
    except json.JSONDecodeError:
        creds = Credentials.from_service_account_file(service_account_value, scopes=scope)
    client = gspread.authorize(creds)

    spreadsheet = client.open_by_url(sheet_url)
    worksheet = spreadsheet.get_worksheet(0)

    # Map each country to its (value column letter, url column letter) in the sheet
    # Columns: B=Brand name, C=Keyword, D=Store name, E=SG, F=MY, G=HK, H=ID,
    #          I=Store Redirection Status, J=Date Time Added, K=SG url, L=MY url, M=HK url, N=ID url
    country_col_map = {
        'SG': ('E', 'K'),
        'MY': ('F', 'L'),
        'HK': ('G', 'M'),
        'ID': ('H', 'N'),
    }

    # Get existing data from sheet
    try:
        existing_data = worksheet.get_all_records()
        if existing_data:
            existing_df = pd.DataFrame(existing_data)
            log(f"Found {len(existing_df)} existing records in sheet")

            # Build lookup: {(Brand name, Store name): (sheet_row_number, row_data)}
            existing_lookup = {}
            for i, (_, row) in enumerate(existing_df.iterrows()):
                key = (str(row['Brand name']).rstrip(), str(row['Store name']).rstrip())
                sheet_row = i + 2  # +2: row 1 is header, data starts at row 2
                existing_lookup[key] = (sheet_row, row)

            new_records = []
            batch_updates = []

            for _, row in df.iterrows():
                key = (str(row['Brand name']).rstrip(), str(row['Store name']).rstrip())
                if key not in existing_lookup:
                    new_records.append(row)
                else:
                    # Row already exists — update any country column that was 0 but is now 1
                    sheet_row, existing_row = existing_lookup[key]
                    for country in countries:
                        new_val = row.get(country, 0)
                        try:
                            existing_val = int(existing_row.get(country, 0))
                        except (ValueError, TypeError):
                            existing_val = 0
                        if new_val == 1 and existing_val == 0:
                            country_col, url_col = country_col_map[country]
                            url_val = row.get(f'{country} url', '')
                            batch_updates.append({
                                'range': f'{country_col}{sheet_row}',
                                'values': [[1]]
                            })
                            batch_updates.append({
                                'range': f'{url_col}{sheet_row}',
                                'values': [[url_val]]
                            })

            if batch_updates:
                worksheet.batch_update(batch_updates)
                log(f"Updated {len(batch_updates) // 2} existing records with new country/URL data")

            if new_records:
                new_df = pd.DataFrame(new_records)

                # Append new data below existing data (No column handled by SEQUENCE formula)
                last_row = len(existing_df) + 2  # +2 because of header
                set_with_dataframe(worksheet, new_df, row=last_row, col=2, include_index=False, include_column_header=False)  # Start from column B

                # Update SEQUENCE formula to include all rows
                worksheet.update_acell('A2', '=SEQUENCE(COUNTA(B2:B))')

                log(f"Appended {len(new_df)} new records to Google Sheets")
            else:
                log("No new records to add - all data already exists in sheet")
        else:
            # No existing data, add everything with headers
            # First add the header for "No" column
            worksheet.update_acell('A1', 'No')
            # Then add the data starting from column B
            set_with_dataframe(worksheet, df, row=1, col=2, include_index=False, include_column_header=True)
            # Add SEQUENCE formula for numbering
            worksheet.update_acell('A2', '=SEQUENCE(COUNTA(B2:B))')
            log("Added data to empty Google Sheets")
            
    except Exception as e:
        log(f"Error reading existing data, adding all data with headers: {e}")
        # If error reading existing data, overwrite with new data
        # First add the header for "No" column
        worksheet.update_acell('A1', 'No')
        # Then add the data starting from column B
        set_with_dataframe(worksheet, df, row=1, col=2, include_index=False, include_column_header=True)
        # Add SEQUENCE formula for numbering
        worksheet.update_acell('A2', '=SEQUENCE(COUNTA(B2:B))')
        log("Added data to Google Sheets")


def exporter_run(data):
    """Main function to orchestrate the data processing"""
    
    # Process data 
    result = process_brand_data(data)
    
    # Create dataframe
    df = create_dataframe(result)
    
    # Export to Google Sheets
    export_to_google_sheets(df)
    
    log("Data processing completed successfully!")